### ISSUE TITLE
r2d2_redis_patch – Crate that should have been a PR? 

### ISSUE THREAD

**Issue by dvdplm** [nevdelap/r2d2-redis#13]
Hi,
I ran into some trouble today using this crate and ended up trying https://github.com/nottxy/r2d2-redis instead and it worked. I think the only change (https://github.com/nottxy/r2d2-redis/commit/a87fd7b81872508c637bc626ed9070cad594debd) is a mere r2d2 version upgrade and could perhaps have been a PR here instead. The issues feature on that repo is disabled so I'm opening one here instead.

**Comment by badboy** [comment]
It needs a bit more, see #14

**Comment by sorccu** [comment]
Yeah, we generally update the crate as long as someone actually tells us when something breaks with newer versions. Thanks for letting us know @dvdplm and good work @badboy.
