### ISSUE TITLE
main example broken

### ISSUE THREAD

**Issue by bklooste** [nevdelap/r2d2-redis#3]
src/main.rs:22:60: 22:72 error: the trait `redis::connection::ConnectionLike` is not implemented for the type `redis::client::Client` [E0277]
src/main.rs:22             let reply = redis::cmd("PING").query::<String>(conn.deref()).unwrap();

using toml 
r2d2 = "_"
r2d2_redis = "_"

[dependencies.redis]
version = "*"
features = ["unix_socket"]

**Comment by ray-delossantos** [comment]
I'm having the same kind of error.

**Comment by sorccu** [comment]
If you're using redis crate 0.5.1, the currently published r2d2_redis 0.1.0 actually uses 0.3.1. `cargo` happily builds both versions but they are then of course incompatible, leading to massive confusion. #5 would solve this.

**Comment by nevdelap** [comment]
Sorry everyone. I need someone to take over being maintainer of this. I am not actively doing anything rust related sadly because of being too busy in other work and non-IT related studies. Anyone want to take it over?

**Comment by sorccu** [comment]
Well, I'm using rust and r2d2_redis every day, so I can take over if you like.

**Comment by nevdelap** [comment]
Hi sorccu and badboy,

You have both said you can. Do you want to email me at xxxxxxxx so we can make the transfer to whichever of you you think will most likely be able to maintain it long term?

Cheers.

PS: I'm GMT+10.

**Comment by sorccu** [comment]
Resolved as of 0.2.0.
