### ISSUE TITLE
r2d2_redis::r2d2 is conflicting with r2d2_postgres::r2d2

### ISSUE THREAD

**Issue by yonathanYPP** [nevdelap/r2d2-redis#41]
i've try to implement th example code, but it return an error 
td::result::Result<pkg::redis::r2d2_redis::RedisConnectionManager, pkg::redis::r2d2_redis::redis::RedisError>: database::connection::r2d2_postgres::r2d2::ManageConnection` is not satisfied
required by `database::connection::r2d2_postgres::r2d2::Pool::<M>::builder`rustc(E0277)

database connection is my package that use r2d2_postgres, need any help thanks.

**Comment by badboy** [comment]
Make sure to use a _single_ version of `r2d2` in your dependency tree.

Also please do surround code with triple-backticks (```) for easier reading.
Additionally provide not just the error, but also sample code, otherwise all we can do is guess, but not really help.

Closing as there's not much more we can help with.
