### ISSUE TITLE
redis cluster support

### ISSUE THREAD

**Issue by glensc** [nevdelap/r2d2-redis#44]
does this library support redis cluster?

- https://github.com/sorccu/r2d2-redis/blob/e6ed5be94fa7da19fb30d6fb2ddc0b0f8f83a7a5/examples/ping.rs#L9

how to connect to cluster? how to specify multiple nodes?

redis cluster docs:
- https://redis.io/topics/cluster-tutorial

**Comment by glensc** [comment]
seems this project users redis crate:
- https://crates.io/crates/redis

**Comment by glensc** [comment]
and there's some mention of cluster:
- https://docs.rs/redis/0.17.0/redis/#optional-features

but seems different module needs to be used for cluster:
- https://docs.rs/redis/0.17.0/redis/cluster/index.html

**Comment by mlh758** [comment]
This is just a wrapper library that provides connection pooling. All the r2d2 projects are like that. https://docs.rs/r2d2/0.8.9/r2d2/
